---
created: '2021-02-25T10:16:30.268028Z'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
app-depth-max:
  hash: null
  component:
    app-depth-max (exception of system takes precedence)
      exception (ignored because this variant does not have a contributing stacktrace, but the system variant does)
        stacktrace (discarded because stack trace only contains 1 frame which is under the configured threshold by stack trace rule (family:native min-frames=2))
          frame (non app frame)
            function*
              "_main"
          frame (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
            package
              "std"
          frame (non app frame)
            function*
              "___rust_maybe_catch_panic"
          frame (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package
              "std"
          frame (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
            package
              "std"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
            package
              "log_demo"
          frame (non app frame)
            function*
              "log::__private_api_log"
            package
              "log"
        type*
          "log_demo"
        value*
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system:
  hash: "e0b4eea234ff891472cb927c00153bbe"
  component:
    system*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
            package
              "std"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package
              "std"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start::{{closure}}"
            package
              "std"
          frame* (marked in-app by stack trace rule (function:log_demo::* +app))
            function*
              "log_demo::main"
            package
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
